# Set user/password as root
version: '3'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: api
    volumes:
      - $HOME/Development/Volumes/mongo/data/db:/data/db
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge